<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-0HSGMNA0" failures="3" tests="34" name="automation.testing.AutomatedTests" time="213.435" errors="0" timestamp="2021-04-03T17:36:29 IST" skipped="0">
  <testcase classname="automation.testing.AutomatedTests" name="TC_01" time="1.260"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_02" time="3.661"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_03" time="4.190"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_03" time="4.933"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_04" time="5.631"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_05" time="5.378"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_06" time="7.415"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_07" time="6.290"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_08" time="6.900"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_09" time="4.924"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_09" time="4.966"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_10" time="5.052"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_11" time="2.336"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_11" time="2.568"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_12" time="1.887"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_13" time="5.280"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_14" time="5.014"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_14" time="5.166"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_15" time="5.947"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_16" time="12.595"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_17" time="5.609"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_18" time="11.497"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_18" time="12.158"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_19" time="11.462"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_20" time="7.349"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_21" time="7.034"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_22" time="7.521"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_23" time="7.874"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_24" time="6.399"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_25" time="6.364">
    <failure message="The following asserts failed:
	The user didn&#039;t get any error message for filling invalid &quot;Recipient&#039;s Email&quot; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
The user didn't get any error message for filling invalid "Recipient's Email" expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at automation.testing.TestScripts.tc_25_InvalidRecipientEmail(TestScripts.java:813)
at automation.testing.AutomatedTests.TC_25(AutomatedTests.java:164)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_25 -->
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_26" time="7.475"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_27" time="8.289"/>
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_28" time="5.903">
    <failure message="The following asserts failed:
	The user didn&#039;t get any error message for filling invalid &quot;Recipient&#039;s Name&quot; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
The user didn't get any error message for filling invalid "Recipient's Name" expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at automation.testing.TestScripts.tc_28_InvalidRecipientName(TestScripts.java:977)
at automation.testing.AutomatedTests.TC_28(AutomatedTests.java:179)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_28 -->
  <system-out/>
  <testcase classname="automation.testing.AutomatedTests" name="TC_29" time="7.108">
    <failure message="The following asserts failed:
	The user didn&#039;t get any error message for filling invalid &quot;Your Name&quot; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
The user didn't get any error message for filling invalid "Your Name" expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at automation.testing.TestScripts.tc_29_InvalidYourName(TestScripts.java:1032)
at automation.testing.AutomatedTests.TC_29(AutomatedTests.java:184)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_29 -->
  <system-out/>
</testsuite> <!-- automation.testing.AutomatedTests -->
